title: Debian-Linux.cz
subtitle: zpravodajství z distribuce Debian
description: Debian-Linux.cz podporuje operační systém GNU/Linux Debian především v České republice. Denně přináší zpravodajství, návody a zajímavosti.
keywords: Linux, GNU/Linux, Debian, distribuce, operační systém, zprávy, novinky

remote_content:
  - name: 'rootcz-debian'
    url: 'https://www.root.cz/rss/n/debian/'
  - name: 'debian-org-news'
    url: 'https://www.debian.org/News/news'
  - name: 'planet-debian'
    url: 'https://planet.debian.org/rss20.xml'

merge_rss:
  - key: all
    title: 'Co je nového'
    feeds:
      - 'rootcz-debian'
      - 'debian-org-news'

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: cs
logo: /assets/images/debian-logo.svg
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: https://www.twitter.com/debiancz
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/pages/Debian-linuxcz/172367506107326
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/DebianLinuxCZ/
atom_feed:
  path: /feed/ # blank (default) uses feed.xml
analytics: # requires 'JEKYLL_ENV=production'
  provider: google-universal # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-3266139-3
    anonymize_ip: true # true, false (default)

feed:
  path: /feed/

# Build settings
markdown: kramdown
include: [
    '/_pages',
]
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
plugins:
  - jekyll-sitemap
  - jekyll-tidy
