title: Debian-Linux.cz
subtitle: zpravodajství z distribuce Debian
description: Debian-Linux.cz podporuje operační systém GNU/Linux Debian především v České republice. Denně přináší zpravodajství, návody a zajímavosti.
keywords: Linux, GNU/Linux, Debian, distribuce, operační systém, zprávy, novinky

remote_content:
  - name: 'rootcz-debian'
    url: 'https://www.root.cz/rss/n/debian/'
  - name: 'forum'
    url: 'https://forum.debian-linux.cz/index.php?type=rss2;action=.xml;sa=news'
  - name: 'debian-org-news'
    url: 'https://www.debian.org/News/news'

merge_rss:
  - key: news
    title: 'Co je nového'
    feeds:
      - 'rootcz-debian'
      - 'debian-org-news'

generate_rss:
  from: news
  link: 'https://www.debian-linux.cz'
  path: /feed

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: cs
logo: /assets/images/debian-logo.svg
copyright_url: /o-tomto-webu/
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: https://www.twitter.com/debiancz
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/pages/Debian-linuxcz/172367506107326
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/DebianLinuxCZ/
atom_feed:
  path: /feed # same as generate_rss.path above
analytics: # requires 'JEKYLL_ENV=production'
  provider: google-universal # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-3266139-3
    anonymize_ip: true # true, false (default)

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed
include: [
    '/_pages',
]
exclude:
  - vendor
  - README.md
  - scripts
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-tidy
