title: Debian-Linux.cz
subtitle: zpravodajství z distribuce Debian
description: Debian-Linux.cz podporuje operační systém GNU/Linux Debian především v České republice. Denně přináší zpravodajství, návody a zajímavosti.
keywords: Linux, GNU/Linux, Debian, distribuce, operační systém, zprávy, novinky

remote_content:
  - name: 'forum'
    url: 'https://forum.debian-linux.cz/index.php?type=rss2;action=.xml;sa=news'

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: cs
logo: /assets/images/debian-logo.svg
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: https://www.twitter.com/debiancz
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/pages/Debian-linuxcz/172367506107326
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/DebianLinuxCZ/
atom_feed:
  path: /feed/ # blank (default) uses feed.xml
analytics: # requires 'JEKYLL_ENV=production'
  provider: google-universal # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-3266139-3
    anonymize_ip: true # true, false (default)

feed:
  path: /feed/

# Build settings
markdown: kramdown
include: [
    '/_pages',
]
exclude:
  - _lib
  - vendor
  - scripts
  - Makefile
  - README.md
  - planet.db
  - planet.ini
plugins:
  - jekyll-sitemap
  - jekyll-tidy
